// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is auto-generated by the build_runner package using json_serializable
// Any manual changes will be overwritten when the generator runs again

// Declares this file as part of the 'global_data_model.dart' library
part of 'global_data_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// Code generated by the json_serializable package for JSON serialization
// **************************************************************************

/// Deserializes JSON into a GlobalDataModel object
/// Takes a Map with String keys and dynamic values (typical JSON structure)
/// Returns a fully constructed GlobalDataModel instance
GlobalDataModel _$GlobalDataModelFromJson(Map<String, dynamic> json) =>
    GlobalDataModel(
      // Extracts the 'data' field from JSON, casts it to a Map, and converts it to GlobalData object
      data: GlobalData.fromJson(json['data'] as Map<String, dynamic>),
    );

/// Serializes a GlobalDataModel object into JSON format
/// Takes a GlobalDataModel instance and returns a Map representing JSON structure
Map<String, dynamic> _$GlobalDataModelToJson(GlobalDataModel instance) =>
    <String, dynamic>{
      // Maps the 'data' property to the JSON key 'data'
      // json_serializable will automatically call toJson on the GlobalData object
      'data': instance.data,
    };

/// Deserializes JSON into a GlobalData object
/// Converts API response data into strongly-typed Dart objects
GlobalData _$GlobalDataFromJson(Map<String, dynamic> json) => GlobalData(
      // Extracts 'active_cryptocurrencies' from JSON, casts to num, then converts to int
      // Represents the total number of active cryptocurrencies in the market
      activeCryptocurrencies: (json['active_cryptocurrencies'] as num).toInt(),

      // Transforms the 'total_market_cap' map from JSON into a Map<String, double>
      // The outer map contains currency codes as keys (e.g., 'usd', 'eur') and market cap values
      totalMarketCap: (json['total_market_cap'] as Map<String, dynamic>).map(
        // For each entry: k = currency code, e = market cap value
        // Converts each value from num to double and creates a new MapEntry
        (k, e) => MapEntry(k, (e as num).toDouble()),
      ),

      // Transforms the 'total_volume' map from JSON into a Map<String, double>
      // Contains 24-hour trading volumes in different currencies
      totalVolume: (json['total_volume'] as Map<String, dynamic>).map(
        // k = currency code (e.g., 'usd'), e = volume value
        // Converts the volume value to double for precise calculations
        (k, e) => MapEntry(k, (e as num).toDouble()),
      ),

      // Transforms the 'market_cap_percentage' map from JSON into a Map<String, double>
      // Shows each cryptocurrency's percentage of the total market cap
      marketCapPercentage:
          (json['market_cap_percentage'] as Map<String, dynamic>).map(
        // k = cryptocurrency symbol, e = percentage value
        // Converts percentage to double (e.g., 42.5 for 42.5%)
        (k, e) => MapEntry(k, (e as num).toDouble()),
      ),

      // Extracts the 24-hour market cap change percentage in USD
      // Converts from num to double for decimal precision
      // Positive values indicate market growth, negative indicate decline
      marketCapChangePercentage24hUsd:
          (json['market_cap_change_percentage_24h_usd'] as num).toDouble(),
    );

/// Serializes a GlobalData object into JSON format
/// Converts Dart objects back to JSON-compatible Map structure for API requests or storage
Map<String, dynamic> _$GlobalDataToJson(GlobalData instance) =>
    <String, dynamic>{
      // Maps the activeCryptocurrencies property to JSON key 'active_cryptocurrencies'
      'active_cryptocurrencies': instance.activeCryptocurrencies,

      // Maps the totalMarketCap Map to JSON key 'total_market_cap'
      // The Map<String, double> is directly serializable to JSON
      'total_market_cap': instance.totalMarketCap,

      // Maps the totalVolume Map to JSON key 'total_volume'
      'total_volume': instance.totalVolume,

      // Maps the marketCapPercentage Map to JSON key 'market_cap_percentage'
      'market_cap_percentage': instance.marketCapPercentage,

      // Maps the 24h market cap change percentage to JSON key
      'market_cap_change_percentage_24h_usd':
          instance.marketCapChangePercentage24hUsd,
    };
