// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is auto-generated by build_runner using json_serializable
// Any manual changes will be overwritten when the generator runs again

// Declares this file as part of the 'top_gainer_model.dart' library
part of 'top_gainer_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// Code generated by the json_serializable package for JSON serialization
// **************************************************************************

/// Deserializes JSON into a TopGainerModel object
/// Extracts all cryptocurrency market data fields from the API response
TopGainerModel _$TopGainerModelFromJson(Map<String, dynamic> json) =>
    TopGainerModel(
      // Basic identification fields
      id: json['id'] as String, // Unique coin identifier
      symbol: json['symbol'] as String, // Trading symbol/ticker
      name: json['name'] as String, // Full coin name
      image: json['image'] as String, // URL to coin logo

      // Price and market data
      currentPrice: (json['current_price'] as num).toDouble(), // Current price in selected currency
      marketCap: (json['market_cap'] as num).toDouble(), // Total market capitalization
      marketCapRank: (json['market_cap_rank'] as num?)?.toInt(), // Rank by market cap (nullable)
      fullyDilutedValuation:
          (json['fully_diluted_valuation'] as num?)?.toDouble(), // FDV (nullable)
      totalVolume: (json['total_volume'] as num).toDouble(), // 24h trading volume

      // 24-hour price range
      high24h: (json['high_24h'] as num?)?.toDouble(), // 24h high price (nullable)
      low24h: (json['low_24h'] as num?)?.toDouble(), // 24h low price (nullable)

      // 24-hour changes
      priceChange24h: (json['price_change_24h'] as num?)?.toDouble(), // Absolute price change (nullable)
      priceChangePercentage24h:
          (json['price_change_percentage_24h'] as num?)?.toDouble(), // Percentage price change (nullable)
      marketCapChange24h: (json['market_cap_change_24h'] as num?)?.toDouble(), // Absolute market cap change (nullable)
      marketCapChangePercentage24h:
          (json['market_cap_change_percentage_24h'] as num?)?.toDouble(), // Percentage market cap change (nullable)

      // Supply metrics
      circulatingSupply: (json['circulating_supply'] as num?)?.toDouble(), // Coins in circulation (nullable)
      totalSupply: (json['total_supply'] as num?)?.toDouble(), // Total existing coins (nullable)
      maxSupply: (json['max_supply'] as num?)?.toDouble(), // Maximum possible supply (nullable)

      // All-time high (ATH) data
      ath: (json['ath'] as num?)?.toDouble(), // All-time high price (nullable)
      athChangePercentage: (json['ath_change_percentage'] as num?)?.toDouble(), // % change from ATH (nullable)
      athDate: json['ath_date'] as String?, // Date of ATH (nullable)

      // All-time low (ATL) data
      atl: (json['atl'] as num?)?.toDouble(), // All-time low price (nullable)
      atlChangePercentage: (json['atl_change_percentage'] as num?)?.toDouble(), // % change from ATL (nullable)
      atlDate: json['atl_date'] as String?, // Date of ATL (nullable)

      // Metadata
      lastUpdated: json['last_updated'] as String, // Last update timestamp
    );

/// Serializes a TopGainerModel object into JSON format
/// Maps all model properties back to their corresponding JSON keys
Map<String, dynamic> _$TopGainerModelToJson(TopGainerModel instance) =>
    <String, dynamic>{
      // Basic identification
      'id': instance.id,
      'symbol': instance.symbol,
      'name': instance.name,
      'image': instance.image,

      // Price and market data
      'current_price': instance.currentPrice,
      'market_cap': instance.marketCap,
      'market_cap_rank': instance.marketCapRank,
      'fully_diluted_valuation': instance.fullyDilutedValuation,
      'total_volume': instance.totalVolume,

      // 24-hour price range
      'high_24h': instance.high24h,
      'low_24h': instance.low24h,

      // 24-hour changes
      'price_change_24h': instance.priceChange24h,
      'price_change_percentage_24h': instance.priceChangePercentage24h,
      'market_cap_change_24h': instance.marketCapChange24h,
      'market_cap_change_percentage_24h': instance.marketCapChangePercentage24h,

      // Supply metrics
      'circulating_supply': instance.circulatingSupply,
      'total_supply': instance.totalSupply,
      'max_supply': instance.maxSupply,

      // All-time high (ATH)
      'ath': instance.ath,
      'ath_change_percentage': instance.athChangePercentage,
      'ath_date': instance.athDate,

      // All-time low (ATL)
      'atl': instance.atl,
      'atl_change_percentage': instance.atlChangePercentage,
      'atl_date': instance.atlDate,

      // Metadata
      'last_updated': instance.lastUpdated,
    };
