// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is auto-generated by build_runner using json_serializable
// Any manual changes will be overwritten when the generator runs again

// Declares this file as part of the 'trending_coin_model.dart' library
part of 'trending_coin_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// Code generated by the json_serializable package for JSON serialization
// **************************************************************************

/// Deserializes JSON into a TrendingCoinsModel object
/// Extracts the 'coins' array and converts each item to TrendingCoinItem
TrendingCoinsModel _$TrendingCoinsModelFromJson(Map<String, dynamic> json) =>
    TrendingCoinsModel(
      // Extracts 'coins' as a List, maps each element to TrendingCoinItem, converts to List
      coins: (json['coins'] as List<dynamic>)
          .map((e) => TrendingCoinItem.fromJson(e as Map<String, dynamic>))
          .toList(),
    );

/// Serializes TrendingCoinsModel to JSON
/// The coins list will be automatically serialized by json_serializable
Map<String, dynamic> _$TrendingCoinsModelToJson(TrendingCoinsModel instance) =>
    <String, dynamic>{
      'coins': instance.coins, // List of trending coin items
    };

/// Deserializes JSON into a TrendingCoinItem object
/// Handles the API's nested 'item' structure for each trending coin
TrendingCoinItem _$TrendingCoinItemFromJson(Map<String, dynamic> json) =>
    TrendingCoinItem(
      // Extracts the nested 'item' object and converts to TrendingCoin
      item: TrendingCoin.fromJson(json['item'] as Map<String, dynamic>),
    );

/// Serializes TrendingCoinItem to JSON
/// Wraps the trending coin data in an 'item' field
Map<String, dynamic> _$TrendingCoinItemToJson(TrendingCoinItem instance) =>
    <String, dynamic>{
      'item': instance.item, // Nested trending coin data
    };

/// Deserializes JSON into a TrendingCoin object
/// Extracts all trending coin fields including identification, images, and nested data
TrendingCoin _$TrendingCoinFromJson(Map<String, dynamic> json) => TrendingCoin(
      id: json['id'] as String, // Unique coin identifier
      coinId: (json['coin_id'] as num).toInt(), // CoinGecko numeric ID
      name: json['name'] as String, // Full coin name
      symbol: json['symbol'] as String, // Trading symbol/ticker
      thumb: json['thumb'] as String, // Thumbnail image URL
      small: json['small'] as String, // Small image URL
      large: json['large'] as String, // Large image URL
      slug: json['slug'] as String, // URL-friendly identifier
      priceBtc: (json['price_btc'] as num).toDouble(), // Price in Bitcoin
      score: (json['score'] as num).toInt(), // Trending score (popularity)
      data: TrendingCoinData.fromJson(json['data'] as Map<String, dynamic>), // Nested market data
    );

/// Serializes TrendingCoin to JSON
/// Maps all trending coin properties to their corresponding JSON keys
Map<String, dynamic> _$TrendingCoinToJson(TrendingCoin instance) =>
    <String, dynamic>{
      'id': instance.id,
      'coin_id': instance.coinId,
      'name': instance.name,
      'symbol': instance.symbol,
      'thumb': instance.thumb,
      'small': instance.small,
      'large': instance.large,
      'slug': instance.slug,
      'price_btc': instance.priceBtc,
      'score': instance.score,
      'data': instance.data, // Nested TrendingCoinData object
    };

/// Deserializes JSON into a TrendingCoinData object
/// Extracts market data fields with dynamic types to handle varying API formats
TrendingCoinData _$TrendingCoinDataFromJson(Map<String, dynamic> json) =>
    TrendingCoinData(
      price: json['price'], // Current price (dynamic type)
      priceBtc: json['price_btc'], // Price in BTC (dynamic type)
      priceChangePercentage24h:
          json['price_change_percentage_24h'] as Map<String, dynamic>?, // 24h % changes by currency (nullable)
      marketCap: json['market_cap'], // Market capitalization (dynamic type)
      totalVolume: json['total_volume'], // Trading volume (dynamic type)
    );

/// Serializes TrendingCoinData to JSON
/// Maps all market data properties to their corresponding JSON keys
Map<String, dynamic> _$TrendingCoinDataToJson(TrendingCoinData instance) =>
    <String, dynamic>{
      'price': instance.price,
      'price_btc': instance.priceBtc,
      'price_change_percentage_24h': instance.priceChangePercentage24h,
      'market_cap': instance.marketCap,
      'total_volume': instance.totalVolume,
    };
